# Generated by Django 6.0.6 on 2026-06-15 19:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_location", models.CharField(max_length=255)),
                ("pickup_location", models.CharField(max_length=255)),
                ("dropoff_location", models.CharField(max_length=255)),
                (
                    "current_cycle_used",
                    models.FloatField(
                        help_text="Hours used in current 70hr/8day cycle",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(70),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RouteSegment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_location", models.CharField(max_length=255)),
                ("end_location", models.CharField(max_length=255)),
                ("distance_miles", models.FloatField()),
                ("duration_hours", models.FloatField()),
                ("is_driving", models.BooleanField(default=True)),
                ("is_fuel_stop", models.BooleanField(default=False)),
                ("is_rest_break", models.BooleanField(default=False)),
                ("order", models.IntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="segments",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="EldLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("day_number", models.IntegerField()),
                ("date", models.DateField()),
                ("driving_hours", models.FloatField()),
                ("on_duty_hours", models.FloatField()),
                ("off_duty_hours", models.FloatField()),
                ("sleeper_berth_hours", models.FloatField()),
                ("total_miles", models.FloatField()),
                ("cycle_hours_remaining", models.FloatField(blank=True, null=True)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="eld_logs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ["trip", "day_number"],
            },
        ),
    ]
